matrix:
  include:
    - language: go

    go:
      - "1.10.1"
      - master

    install: true

    matrix:
      allow_failures:
        - go: master

      fast_finish: true

    before_script:
      - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

    script:
      - test -z $(gofmt -s -l $GO_FILES)

  include:
    - language: node_js

    node_js:
      - "10.0.0"
      - master

    matrix:
      allow_failures:
        - node_js: master

      fast_finish: true

    script:
      - npm test

notifications:
  email: false