matrix:
  include:
    - language: go
    go:
      - "1.10.1"
      - master
    before_install:

  include:
    - language: node_js
    node_js:
      - "10.0.0"
      - master
    script:
      - npm run lint
      - npm test
    after_success:
      - npm run coverage